=== blackforest-t/tbtapi-docs/edi/json-schema/fms_contragent_announcement.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "FMS contragent events",
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    }
  },
  "required": [
    "sender",
    "timestamp",
    "contragent_id",
    "contragent_reg_id",
    "action",
    "reason"
  ],
  "properties": {
    "sender": {
      "type": "string",
      "description": "Sender name",
      "enum": [
        "tbt"
      ]
    },
    "timestamp": {
      "description": "Send time",
      "type": "string",
      "format": "date-time"
    },
    "contragent_id": {
      "$ref": "#/definitions/uuid",
      "description": "Contragent identifier"
    },
    "contragent_reg_id": {
      "type": "string",
      "description": "Contragent external/state identifier"
    },
    "action": {
      "type": "string",
      "description": "action",
      "enum": [
        "created",
        "deleted",
        "updated",
        "blocked",
        "disabled"
      ]
    },
    "reason": {
      "type": "string",
      "description": "reason",
      "enum": [
        "self",
        "requisites",
        "fraud",
        "disaster",
        "other"
      ]
    },
    "merchant_id": {
      "anyOf": [
        {
          "type": "string",
          "description": "Payment system contragent identifier"
        },
        {
          "type": "null"
        }
      ]
    },
    "comment": {
      "type": "string",
      "description": "Additional info"
    },
    "msg_for": {
      "$ref": "#/definitions/uuid",
      "description": "User id to proxy message for"
    },
    "group": {
      "$ref": "#/definitions/uuid",
      "description": "Agent group"
    }
  }
}

=== blackforest-t/tbtapi-docs/tests/edi/json-schema/fms_contragent_announcement.json
{
  "sender": "tbt",
  "timestamp": "2020-03-23T17:07:33.438Z",
  "contragent_id": "5af4985c-ac0d-23c9-710c-8c4e8b31f69a",
  "contragent_reg_id": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  "action": "deleted",
  "reason": "self",
  "merchant_id": "ABCDEFGHIJKLMNOPQR",
  "comment": "ABCDEFGHIJK",
  "msg_for": "deeaea34-ff10-48dd-bf54-82add4b931de"
}
