=== blackforest-t/tbtapi-docs/edi/json-schema/refill_payment.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Wallet replenishment event",
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    }
  },
  "required": [
     "sender", "timestamp", "id", "payer_phone", "dest",
     "posop", "posorder_id", "merchant_id", "amount"
  ],
  "properties": {
    "sender": {
      "type": "string",
      "description": "Sender name",
      "enum": ["tabata", "tbt"]
    },
    "timestamp": {
      "description": "Transaction time",
      "type": "string",
      "format": "date-time"
    },
    "id": {
      "$ref": "#/definitions/uuid",
      "description": "Transaction identifier"
    },
    "payer_phone": {
      "type": "string",
      "description": "Payer phone number",
      "pattern": "^380[0-9]{9}$"
    },
    "user_id": {
      "type": "string",
      "description": "Payer identifier"
    },
    "dest": {
      "type": "string",
      "description": "Replenishment destination",
      "enum": ["wallet", "card"]
    },
    "posop": {
      "type": "string",
      "description": "Payment processor identifier",
      "enum": ["fcs_term"]
    },
    "posorder_id": {
      "type": "string",
      "description": "Payment system transaction identifier"
    },
    "merchant_id": {
      "type": "string",
      "description": "Payment system contragent identifier"
    },
    "amount": {
      "type": "string",
      "description": "Transaction money total",
      "pattern": "^[0-9]{1,5}(\\.[0-9]{1,2})?$"
    },
    "comment": {
      "type": "string",
      "description": "Additional info"
    },
    "msg_for": {
      "$ref": "#/definitions/uuid",
      "description": "User id to proxy message for"
    },
    "group": {
      "$ref": "#/definitions/uuid",
      "description": "Agent group"
    }
  }
}

=== blackforest-t/tbtapi-docs/tests/edi/json-schema/refill_payment.json
{
  "sender": "tbt",
  "timestamp": "2020-03-23T17:07:33.438Z",
  "id": "f3d9cddc-9f71-b0d6-e634-2010ccfc800a",
  "payer_phone": "380837038206",
  "user_id": "ABCDEFGHIJKLMNOPQRSTU",
  "dest": "wallet",
  "posop": "fcs_term",
  "posorder_id": "ABCDEF",
  "merchant_id": "ABCDEFGHIJKLMNOPQRSTUVWX",
  "amount": "3.90",
  "comment": "ABCDEFGHIJKLMNOPQRSTU"
}
