=== blackforest-t/tbtapi-docs/edi/json-schema/wms_event.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "WMS event",
  "definitions": {
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    },
    "uuid_v1": {
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-1[0-9a-fA-F]{3}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
    }
  },
  "type": "object",
  "required": [
    "serial",
    "items",
    "condition"
  ],
  "properties": {
    "serial": {
      "$ref": "#/definitions/uuid_v1"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "condition": {
      "type": "string",
      "enum": [
        "exception", "transition", "exchange", "action"
      ]
    },
    "ev_type": {
      "type": "string",
      "enum": [
        "creating",
        "scanning",
        "marking",
        "placing",
        "processing",
        "sorting",
        "searching",
        "classifying",
        "packing",
        "inventing",
        "unloading",
        "correcting"
      ]
    },
    "ev_task": {
      "type": "string"
    },
    "ev_stage": {
      "type": "string"
    },
    "coordinates": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "flow": {
      "type": "string",
      "enum": [
        "empty", "auto", "unidirectional", "bidirectional"
      ]
    },
    "direction": {
      "type": "string",
      "enum": [
        "direct", "reverse"
      ]
    },
    "reason": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "origin": {
      "$ref": "#/definitions/uuid"
    },
    "owner": {
      "$ref": "#/definitions/uuid"
    },
    "msg_for": {
      "$ref": "#/definitions/uuid",
      "description": "User id to proxy message for"
    },
    "group": {
      "$ref": "#/definitions/uuid",
      "description": "Agent group"
    }
  }
}

=== blackforest-t/tbtapi-docs/tests/edi/json-schema/wms_event.json
{
  "serial": "c861e640-6d28-11ea-b8ee-db02b56522a1",
  "items": ["50000336505771"],
  "condition": "action",
  "ev_type": "sorting",
  "ev_task": "fulfillment",
  "ev_stage": "fulfill",
  "coordinates": [
    "123",
    "456"
  ],
  "flow": "auto",
  "direction": "direct",
  "reason": "ABCDEFGHI",
  "version": "v2019.2",
  "origin": "aac099d5-f520-4c00-95ab-cc445bec8920",
  "owner": "46f69d00-4389-444b-9174-26b1f6f0bafa",
  "msg_for": "deeaea34-ff10-48dd-bf54-82add4b931de",
  "group": "e7f4b2dc-1648-4497-8b43-792c6d8c70c2"
}
